issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - asciicheck
    - errcheck
    - exportloopref
    - gocritic
    - gofmt
    - gomnd
    - gosimple
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - vet
    - vetshadow
    - whitespace

linters-settings:
  errcheck:
    # TODO: `ignore` is deprecated, but `exclude-functions` does not appear to work
    ignore: fmt:.*,github.com/hashicorp/terraform-plugin-framework/tfsdk:SetAttribute,fprintf
    # exclude-functions:
    #   - (*github.com/hashicorp/terraform-plugin-framework/tfsdk.State).SetAttribute
  gocritic:
    enabled-tags:
      - diagnostic
    disabled-tags:
      - style
      - performance
      - experimental
      - opinionated
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - assign
          - case
          # - condition
          - operation
          - return
        ignored-functions:
          - os.Exit
          - validate.StringLenAtMost
          - validate.StringLenBetween
  nolintlint:
    allow-unused: false
  stylecheck:
    checks: ["all", "-ST1003"]
  unparam:
    check-exported: true

run:
  timeout: 10m
