issues:
  max-per-linter: 0
  max-same-issues: 0

linters:
  disable-all: true
  enable:
    - deadcode
    # - errcheck
    # - errorlint
    - goconst
    - gofmt
    # - gomnd
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nolintlint
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - unparam
    - varcheck

linters-settings:
  gomnd:
    settings:
      mnd:
        checks:
          - argument
          - assign
          - case
          # - condition
          - operation
          - return
        ignored-functions:
          - os.Exit
  unparam:
    check-exported: true

run:
  timeout: 10m
