// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package logs

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AwsccLogsLogGroupResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"floop": schema.BoolAttribute{
				Required: true,
			},
		},
	}
}

type AwsccLogsLogGroupModel struct {
	Floop types.Bool `tfsdk:"floop"`
}
