// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_awscc_gen

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func AwsccGenProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type AwsccGenModel struct {
}
