name: Documentation Linters

on:
  push:
    branches:
      - main
      - "release/**"
  pull_request:
    paths:
      - .github/workflows/documentation-linters.yml
      - .github/**.md
      - .markdownlint.yml
      - docs/**
      # - website/**

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: "yes"
          use-verbose-mode: "yes"
          config-file: ".markdownlinkcheck.json"
          folder-path: "docs,.github"
          file-extension: ".md"

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: avto-dev/markdown-lint@v1
        with:
          config: ".markdownlint.yml"
          args: "docs .github/"
