name: Post-Release

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Release"]
    branches: [main]
    types:
      - completed

jobs:
  Changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Update Changelog Header
        id: changelog
        run: |
          CHANGELOG_FILE_NAME="CHANGELOG.md"
          CURR_RELEASE_TAG=$(git describe --abbrev=0 --match='v*.*.*' --tags)
          TAG=${CURR_RELEASE_TAG:1}

          # Add Release Date
          RELEASE_DATE=`date +%B' '%e', '%Y`
          sed -i -e "1 s/$TAG (Unreleased)/[$TAG](https:\/\/github.com\/hashicorp\/${{ github.event.repository.name }}\/releases\/tag\/$CURR_RELEASE_TAG) ($RELEASE_DATE)/" $CHANGELOG_FILE_NAME

          # Prepend next release line
          echo Previous release is: $CURR_RELEASE_TAG

          NEXT_RELEASE_LINE=$(echo $CURR_RELEASE_TAG | awk -F. '{
              $1 = substr($1,2)
              $2 += 1
              printf("%s.%01d.%s\n\n", $1, $2, $3);
          }')

          echo New minor version is: v$NEXT_RELEASE_LINE

          echo -e "## $NEXT_RELEASE_LINE (Unreleased)\n$(cat $CHANGELOG_FILE_NAME)" > $CHANGELOG_FILE_NAME

          echo ::set-output name=curr_release_tag::$CURR_RELEASE_TAG
      - run: |
          git config --local user.email changelogbot@hashicorp.com
          git config --local user.name changelogbot
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md after ${{ steps.changelog.outputs.curr_release_tag }}"
          git push