name: Pre-Release

on:
  workflow_dispatch:

jobs:
  Tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: main
      - name: Get next tag
        id: tag
        run: |
          PREVIOUS_RELEASE_TAG=$(git describe --abbrev=0 --match='v*.*.*' --tags)
          NEW_RELEASE_TAG=v$(echo $PREVIOUS_RELEASE_TAG | awk -F. '{
                        $1 = substr($1,2)
                        $2 += 1
                        printf("%s.%01d.%s\n\n", $1, $2, $3);
                    }')
          echo ::set-output name=new_release_tag::$NEW_RELEASE_TAG
      - name: Create tag
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.tag.outputs.new_release_tag }}",
              sha: context.sha
            })