name: Add new issues to Project
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@1b844f0c5ac6446a402e0cb3693f9be5eca188c5 # v0.6.1
        with:
          project-url: https://github.com/orgs/hashicorp/projects/116
          github-token: ${{ secrets.ORGSCOPED_GITHUB_TOKEN }}
