name: Add new issues to Project
on:
  issues:
    types:
      - opened
jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with:
          project-url: https://github.com/orgs/hashicorp/projects/116
          github-token: ${{ secrets.ORGSCOPED_GITHUB_TOKEN }}
