on:
  - pull_request_target

name: Pull Request Target (All types)
jobs:
  NeedsTriageLabeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
    - name: Apply needs-triage Label
      uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
      if: github.event.action == 'opened' && !contains(fromJSON('["breathingdust", "ewbankkit", "gdavison", "johnsonaj", "YakDriver", "zhelding"]'), github.actor)
      with:
        configuration-path: .github/labeler-pr-needs-triage.yml
        repo-token: ${{ secrets.GITHUB_TOKEN }}
