name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

env:
  GOPROXY: https://proxy.golang.org/

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Read go version
        id: go-version
        run: |
          content=`cat ./.go-version`
          echo "::set-output name=content::$content"
      - uses: actions/setup-go@v2
        with:
          # TODO: Replace with go-version-from-file when it is supported
          # https://github.com/actions/setup-go/pull/62
          go-version: ${{ steps.go-version.outputs.content }}
      - uses: hashicorp/setup-hc-releases@v1
        with:
          github_token: ${{ secrets.HC_RELEASES_TOKEN }}
      - uses: hashicorp/setup-signore@v1
        with:
          client-id: ${{ secrets.SIGNORE_CLIENT_ID }}
          client-secret: ${{ secrets.SIGNORE_CLIENT_SECRET }}
          github-token: ${{ secrets.SIGNORE_GITHUB_TOKEN }}
          signer: interim_signing_subkey_768B676
      - name: Release Notes
        run: sed -n -e "1{/# /d;}" -e "2{/^$/d;}" -e "/# $(git describe --abbrev=0 --exclude="$(git describe --abbrev=0 --match='v*.*.*' --tags)" --match='v*.*.*' --tags | tr -d v)/q;p" CHANGELOG.md > /tmp/RELEASE-NOTES.md
      - name: Release Verson Manifest
        run: |
          VERSION="${$(git describe --tags --abbrev=0):1}"
          cp ./${{ github.event.repository.name }}_manifest.json /tmp/${{ github.event.repository.name }}_${VERSION}_manifest.json
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TF_PROVIDER_RELEASE_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TF_PROVIDER_RELEASE_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          role-to-assume: ${{ secrets.TF_PROVIDER_RELEASE_AWS_ROLE_ARN }}
          role-session-name: ${{ github.run_id }}
      - name: goreleaser release
        uses: goreleaser/goreleaser-action@v2
        with:
          args: release --release-notes /tmp/RELEASE-NOTES.md --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: hc-releases publish
        run: hc-releases publish -product=${{ github.event.repository.name }}
        env:
          FASTLY_API_TOKEN: ${{ secrets.FASTLY_STATIC_PURGE_TOKEN }}
          TERRAFORM_REGISTRY_SYNC_TOKEN: ${{ secrets.TF_PROVIDER_RELEASE_TERRAFORM_REGISTRY_SYNC_TOKEN }}